//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCad.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] BaseScript {
            get {
                object obj = ResourceManager.GetObject("BaseScript", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Operation failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error_operation_failed {
            get {
                return ResourceManager.GetString("error_operation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select two or more object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error_select_2_or_more {
            get {
                return ResourceManager.GetString("error_select_2_or_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select 2 point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error_select_2_points {
            get {
                return ResourceManager.GetString("error_select_2_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string faile_title {
            get {
                return ResourceManager.GetString("faile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document settings ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_doc_settings {
            get {
                return ResourceManager.GetString("menu_doc_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_draw {
            get {
                return ResourceManager.GetString("menu_draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw mesh outline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_draw_mesh_outline {
            get {
                return ResourceManager.GetString("menu_draw_mesh_outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill mesh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_fill_mesh {
            get {
                return ResourceManager.GetString("menu_fill_mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_load {
            get {
                return ResourceManager.GetString("menu_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_new_doc {
            get {
                return ResourceManager.GetString("menu_new_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page settings ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_page_settings {
            get {
                return ResourceManager.GetString("menu_page_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_print {
            get {
                return ResourceManager.GetString("menu_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_save {
            get {
                return ResourceManager.GetString("menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_save_as {
            get {
                return ResourceManager.GetString("menu_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_snap {
            get {
                return ResourceManager.GetString("menu_snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string notice_operation_success {
            get {
                return ResourceManager.GetString("notice_operation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Objects was grouped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string notice_was_grouped {
            get {
                return ResourceManager.GetString("notice_was_grouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Objects was ungrouped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string notice_was_ungrouped {
            get {
                return ResourceManager.GetString("notice_was_ungrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select objects before flip commnad に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string warning_select_objects_before_flip {
            get {
                return ResourceManager.GetString("warning_select_objects_before_flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select objects before flip commnad に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string warning_select_objects_before_flip_and_copy {
            get {
                return ResourceManager.GetString("warning_select_objects_before_flip_and_copy", resourceCulture);
            }
        }
    }
}
